### ISSUE TITLE
Column Error

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#1]
Looks like you have an error in NBA

```
Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 529, in <module>
    main()
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 523, in main
    date, today_games_df = get_todays_games(param, team_list, games_metadf)
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 274, in get_todays_games
    today_games_df['Home Win Prob'] = today_games_df.apply(lambda x: f"{calc_prob(team_name_obj_dict[x['Home Team']], team_name_obj_dict[x['Visiting Team']], param)*100:.2f}%", axis=1)
  File "./NHL-Game-Probabilities/game-probabilities/lib/python3.10/site-packages/pandas/core/frame.py", line 4081, in __setitem__
    self._set_item_frame_value(key, value)
  File "./NHL-Game-Probabilities/game-probabilities/lib/python3.10/site-packages/pandas/core/frame.py", line 4209, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

**Comment by andrewderango** [comment]
Thanks. Needed to update it for the new season. Should be fixed now.
