### ISSUE TITLE
NBA

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#3]
Hello,

I receive the following

```
Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 559, in <module>
    main()
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 553, in main
    date, today_games_df = get_todays_games(param, team_list, games_metadf)
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 285, in get_todays_games
    today_games_df['Home Win Prob'] = today_games_df.apply(lambda row: f"{calc_prob(team_name_obj_dict[row['Home Team']], team_name_obj_dict[row['Visiting Team']], param)*100:.2f}%", axis=1)
  File "./virtualenvs/nhl-game-probabilities/lib/python3.10/site-packages/pandas/core/frame.py", line 4081, in __setitem__
    self._set_item_frame_value(key, value)
  File "./virtualenvs/nhl-game-probabilities/lib/python3.10/site-packages/pandas/core/frame.py", line 4209, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

**Comment by andrewderango** [comment]
Hello,

I can't seem to reproduce the error. Could you please provide additional information on how this error was produced?

**Comment by omar319** [comment]
sorry this seems to be an error on my part! :-)
