### ISSUE TITLE
NHL Error

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#4]
```
raceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 513, in <module>
    main()
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 501, in main
    games_metadf = scrape_nhl_data()
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 126, in scrape_nhl_data
    with urllib.request.urlopen("https://statsapi.web.nhl.com/api/v1/schedule?season=20232024&gameType=R") as url:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by omar319** [comment]
This started occurring on the NHL

**Comment by andrewderango** [comment]
The NHL shut down the legacy version of their API a few days ago. They have a newer version that is about 2 months old, but it has a different structure and endpoints. Restoring the NHL file might take a bit longer, especially because there's a lot less documentation for the new version of the API.

**Comment by andrewderango** [comment]
Just adapted it for the new API. They removed an endpoint that now forces the program to make many more API calls, which increased runtime to about 15s. So I added a progress bar that should help with seeing the live performance of the scraper and give expectations of how long it should take.
