### ISSUE TITLE
Issue with NHL

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#5]
I currently receive this, might have something to do with the data

```
Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 557, in <module>
    main()
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 551, in main
    date, today_games_df = get_todays_games(param, team_list, team_id_dict)
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 294, in get_todays_games
    today_games_df = pd.concat([today_games_df, pd.DataFrame.from_dict([{'GameID':games['id'], 'Game State':'Pre-Game', 'Home Team':team_id_dict[games['homeTeam']['id']], 'Home Goals':games['homeTeam']['score'], 'Away Goals':games['awayTeam']['score'], 'Away Team':team_id_dict[games['awayTeam']['id']], 'Pre-Game Home Win Probability':f'{home_win_prob*100:.2f}%', 'Pre-Game Away Win Probability':f'{away_win_prob*100:.2f}%', 'Home Record':home_team_obj.record, 'Away Record':away_team_obj.record}])], ignore_index=True)
KeyError: 'score'
```

**Comment by andrewderango** [comment]
Should be fixed now. Thanks.
