### ISSUE TITLE
NHL Issue

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#6]
Weird, just pull latest and still the same error

```
Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 557, in <module>
    main()
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 551, in main
    date, today_games_df = get_todays_games(param, team_list, team_id_dict)
  File "./NHL-Game-Probabilities/NHL/nhl_game_probability_model.py", line 296, in get_todays_games
    today_games_df = pd.concat([today_games_df, pd.DataFrame.from_dict([{'GameID':games['id'], 'Game State':f"Period {games['periodDescriptor']['number']}", 'Home Team':team_id_dict[games['homeTeam']['id']], 'Home Goals':games['homeTeam']['score'], 'Away Goals':games['awayTeam']['score'], 'Away Team':team_id_dict[games['awayTeam']['id']], 'Pre-Game Home Win Probability':f'{home_win_prob*100:.2f}%', 'Pre-Game Away Win Probability':f'{away_win_prob*100:.2f}%', 'Home Record':home_team_obj.record, 'Away Record':away_team_obj.record}])], ignore_index=True)
KeyError: 'score'
```

**Comment by andrewderango** [comment]
Strange issue here. The code throws no error when I run it now, but I think this happened because the TOR/CGY game was just starting as you ran the program. I think the game state shifted to "live" but didn't show a score because the time was still at 20:00. I'll add something that I think will fix this issue, but it's difficult to tell if it will work because the error is so rare and difficult to reproduce. Try running it again, and let me know if you get an error.

**Comment by omar319** [comment]
Yeah, running it again worked
